/**
 * Shared types for Frappe trigger maps
 * Auto-generated by harvest-triggers-run.js
 */

export interface FormTriggerMap<T = any> {
  [fieldName: string]: FieldTriggers<T> | ButtonConfig[] | undefined;
  $buttons?: ButtonConfig[];
}

export interface FieldTriggers<T> {
  onChange?: TriggerAction<T>[];
  onBlur?: TriggerAction<T>[];
  onSetup?: TriggerAction<T>[];
}

export type TriggerAction<T> =
  | ValidateAction<T>
  | ServerCallAction<T>
  | SetQueryAction<T>
  | ClearFieldsAction<T>
  | SetValueAction<T>
  | RawAction<T>;

export interface ValidateAction<T> {
  type: "validate";
  rule: (doc: T) => boolean;
  error: string;
  condition?: (doc: T) => boolean;
}

export interface ServerCallAction<T> {
  type: "serverCall";
  method: string;
  args: (doc: T) => Record<string, any>;
  patches: Array<{ field: keyof T; fromResponse: string }>;
  condition?: (doc: T) => boolean;
}

export interface SetQueryAction<T> {
  type: "setQuery";
  targetField: keyof T;
  query: (doc: T) => { query?: string; filters?: Record<string, any> };
}

export interface ClearFieldsAction<T> {
  type: "clearFields";
  fields: Array<keyof T>;
  condition?: (doc: T) => boolean;
}

export interface SetValueAction<T> {
  type: "setValue";
  field: keyof T;
  value: (doc: T) => any;
}

export interface RawAction<T> {
  type: "raw";
  execute: (form: any, doc: T) => void | Promise<void>;
}

export interface ButtonConfig {
  label: string;
  action: string | ((form: any) => void);
  icon?: string;
  condition?: string;
  variant?: "primary" | "secondary" | "danger" | "ghost";
}

// Base controller types
export interface TransactionTriggers<T> {
  company?: { onChange: TriggerAction<T>[] };
  currency?: { onChange: TriggerAction<T>[] };
  posting_date?: { onChange: TriggerAction<T>[] };
}

export interface SellingTriggers<T> extends TransactionTriggers<T> {
  customer?: { onChange: TriggerAction<T>[] };
}

export interface BuyingTriggers<T> extends TransactionTriggers<T> {
  supplier?: { onChange: TriggerAction<T>[] };
}

export interface StockTriggers<T> extends TransactionTriggers<T> {
  warehouse?: { onChange: TriggerAction<T>[] };
  item_code?: { onChange: TriggerAction<T>[] };
}

export interface AccountsTriggers<T> extends TransactionTriggers<T> {
  account?: { onChange: TriggerAction<T>[] };
}

export interface TaxesAndTotalsTriggers<T> {
  tax_category?: { onChange: TriggerAction<T>[] };
  shipping_rule?: { onChange: TriggerAction<T>[] };
}
